openapi: 3.0.0
info:
  title: Jornadas de Futebol
  description: Aqui vai se poder fazer um controlo de uma Jornada de futebol
  contact:
    name: ''
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: DWG localhost
    variables:
      basePath:
        default: /
paths:
  /Temporada:
    get:
      tags:
        - TemporadaController
      summary: Retrieve Temporada
      operationId: retrieveTemporada
      responses:
        '200':
          description: Array of Temporada model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Temporada'
            application/xml:
              schema:
                type: array
                xml:
                  name: Temporada
                items:
                  $ref: '#/components/schemas/Temporada'
      x-swagger-router-controller: TemporadaController
    post:
      tags:
        - TemporadaController
      summary: Create a new Temporada
      operationId: createTemporada
      requestBody:
        description: A new Temporada to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Temporada'
          application/xml:
            schema:
              $ref: '#/components/schemas/Temporada'
      responses:
        '201':
          description: Temporada model instance created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Temporada'
            application/xml:
              schema:
                $ref: '#/components/schemas/Temporada'
      x-swagger-router-controller: TemporadaController
  '/Temporada/{id_temporada}':
    get:
      tags:
        - TemporadaController
      summary: Retrieve Temporada by ID
      operationId: retrieveTemporadaId
      parameters:
        - name: id_temporada
          in: path
          required: true
          style: simple
          explode: false
          schema:
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Temporada'
        '400':
          description: Bad request
        '404':
          description: id not found
      x-swagger-router-controller: TemporadaController
  /Equipa:
    get:
      tags:
        - EquipaController
      summary: Retrieve Equipa
      operationId: retrieveEquipa
      responses:
        '200':
          description: Array of Equipa model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Equipa'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: Temporada
                items:
                  $ref: '#/components/schemas/Equipa'
      x-swagger-router-controller: EquipaController
    post:
      tags:
        - EquipaController
      summary: Create a new Equipa
      operationId: createEquipa
      requestBody:
        description: A new Equipa to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Equipa'
          application/xml:
            schema:
              $ref: '#/components/schemas/Equipa'
      responses:
        '201':
          description: Equipa model instance created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Equipa'
            application/xml:
              schema:
                $ref: '#/components/schemas/Equipa'
      x-swagger-router-controller: EquipaController
  '/Equipa/{id_equipa}':
    get:
      tags:
        - EquipaController
      summary: Retrieve Equipa by ID
      operationId: retrieveEquipaId
      parameters:
        - name: id_equipa
          in: path
          required: true
          style: simple
          explode: false
          schema:
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Equipa'
        '400':
          description: Bad request
        '404':
          description: id not found
      x-swagger-router-controller: EquipaController
  /Estatisticas:
    get:
      tags:
        - EstatisticasController
      summary: Retrieve Estatistica
      operationId: retrieveEstatistica
      responses:
        '200':
          description: Array of Estatisticas model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Estatisticas'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: Estatisticas
                items:
                  $ref: '#/components/schemas/Estatisticas'
      x-swagger-router-controller: EstatisticasController
    post:
      tags:
        - EstatisticasController
      summary: Create a new Estatisticas
      operationId: createEstatisitcas
      requestBody:
        description: A new Estatisticas to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Estatisticas'
          application/xml:
            schema:
              $ref: '#/components/schemas/Estatisticas'
      responses:
        '201':
          description: Estatisticas model instance created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Estatisticas'
            application/xml:
              schema:
                $ref: '#/components/schemas/Estatisticas'
      x-swagger-router-controller: EstatisticasController

      
  '/Estatisticas/{id_estatistica}':
    get:
      tags:
        - EstatisticasController
      summary: Retrieve Estatisticas by ID
      operationId: retrieveEstatisticaId
      parameters:
        - name: id_estatistica
          in: path
          required: true
          style: simple
          explode: false
          schema:
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Estatisticas'
        '400':
          description: Bad request
        '404':
          description: id not found
      x-swagger-router-controller: EstatisticasController
  /Jogador:
    get:
      tags:
        - JogadorController
      summary: Retrieve Jogador
      operationId: retrieveJogador
      responses:
        '200':
          description: Array of Jogador model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Jogador'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: Jogador
                items:
                  $ref: '#/components/schemas/Jogador'
      x-swagger-router-controller: JogadorController
  '/Jogador/{id_jogador}':
    get:
      tags:
        - JogadorController
      summary: Retrieve Jogador by ID
      operationId: retrieveJogadorId
      parameters:
        - name: id_jogador
          in: path
          required: true
          style: simple
          explode: false
          schema:
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jogador'
        '400':
          description: Bad request
        '404':
          description: id not found
      x-swagger-router-controller: JogadorController
  /Jogos:
    get:
      tags:
        - JogosController
      summary: Retrieve Jogos
      operationId: retrieveJogos
      responses:
        '200':
          description: Array of Jogos model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Equipa'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: Jogos
                items:
                  $ref: '#/components/schemas/Equipa'
      x-swagger-router-controller: JogosController
  '/Jogos/{id_jogo}':
    get:
      tags:
        - JogosController
      summary: Retrieve Jogos by ID
      operationId: retrieveJogosId
      parameters:
        - name: id_jogo
          in: path
          required: true
          style: simple
          explode: false
          schema:
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jogos'
        '400':
          description: Bad request
        '404':
          description: id not found
      x-swagger-router-controller: JogosController
  /Ocurrencias:
    get:
      tags:
        - OcurrenciasController
      summary: Retrieve Ocurrencias
      operationId: retrieveOcurrencia
      responses:
        '200':
          description: Array of Ocurrencias model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ocurrencias'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: Ocurrencias
                items:
                  $ref: '#/components/schemas/Ocurrencias'
      x-swagger-router-controller: OcurrenciasController
  '/Ocurrencias/{id_ocurrencia}':
    get:
      tags:
        - OcurrenciasController
      summary: Retrieve Ocurrencias by ID
      operationId: retrieveOcurrenciaId
      parameters:
        - name: id_ocurrencia
          in: path
          required: true
          style: simple
          explode: false
          schema:
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ocurrencias'
        '400':
          description: Bad request
        '404':
          description: id not found
      x-swagger-router-controller: OcurrenciasController
  '/Equipa/{id_equipa}/Temporada':
    get:
      tags:
        - EquipaController
      summary: Retrieve Equipa on temporada
      operationId: retrieveEquipaTemporadaId
      parameters:
        - name: id_equipa
          in: path
          required: true
          style: simple
          explode: false
          schema:
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Temporada'
        '400':
          description: Bad request
        '404':
          description: id not found
      x-swagger-router-controller: EquipaController
components:
  schemas:
    Temporada:
      title: Temporada
      type: object
      properties:
        id_temporada:
          type: integer
          format: int64
        nome_temporada:
          type: string
        pontos_acumulados:
          type: integer
          format: int64
      example:
        id_temporada: 0
        nome_temporada: nome_temporada
        pontos_acumulados: 6
    Equipa:
      title: Equipa
      type: object
      properties:
        id_equipa:
          type: integer
          format: int64
        nome_equipa:
          type: string
      example:
        nome_equipa: nome_equipa
        id_equipa: 0
    Estatisticas:
      title: Estatisticas
      type: object
      properties:
        id_estatistica:
          type: integer
          format: int64
        golos_marcados:
          type: integer
          format: int64
        golos_sofridos:
          type: integer
          format: int64
        faltas_cometidas:
          type: integer
          format: int64
        faltas_sofridas:
          type: integer
          format: int64
      example:
        golos_sofridos: 1
        faltas_sofridas: 5
        id_estatistica: 0
        golos_marcados: 6
        faltas_cometidas: 5
    Jogador:
      title: Jogador
      type: object
      properties:
        id_jogador:
          type: integer
          format: int64
        nome_do_jogador:
          type: string
        numero_do_jogador:
          type: integer
          format: int64
      example:
        numero_do_jogador: 6
        id_jogador: 0
        nome_do_jogador: nome_do_jogador
    Jogos:
      title: Jogos
      type: object
      properties:
        id_jogo:
          type: integer
          format: int64
        resultado:
          type: string
      example:
        resultado: resultado
        id_jogo: 0
    Ocurrencias:
      title: Ocurrencias
      type: object
      properties:
        id_ocurrencia:
          type: integer
          format: int64
        num_faltas:
          type: integer
          format: int64
        num_golos:
          type: integer
          format: int64
        num_cartao:
          type: integer
          format: int64
        minutos:
          type: number
          format: float
        substituicao:
          type: integer
          format: int64
      example:
        num_faltas: 6
        num_cartao: 5
        substituicao: 2
        num_golos: 1
        minutos: 5.637377
        id_ocurrencia: 0
